ClientSupplierMapper/Controllers/SupplierController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ClientSupplierMapper.Models;

namespace ClientSupplierMapper.Controllers
{
    public class SupplierController : Controller
    {
        private ClientSupplierMapperContextModel db = new ClientSupplierMapperContextModel();

        //
        // GET: /Supplier/

        public ActionResult Index()
        {
            return View(db.Suppliers.ToList());
        }

        public ActionResult ViewSuppliers()
        {
            return View(db.Suppliers.ToList());
        }

        //
        // GET: /Supplier/Details/5

        public ActionResult Details(int id = 0)
        {
            Supplier supplier = db.Suppliers.Find(id);
            if (supplier == null)
            {
                return HttpNotFound();
            }
            return View(supplier);
        }

        //
        // GET: /Supplier/Create

        public ActionResult Create()
        {
            return View();
        }

        //
        // POST: /Supplier/Create

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Supplier supplier)
        {
            if (ModelState.IsValid)
            {
                db.Suppliers.Add(supplier);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(supplier);
        }

        //
        // GET: /Supplier/Edit/5

        public ActionResult Edit(int id = 0)
        {
            Supplier supplier = db.Suppliers.Find(id);
            if (supplier == null)
            {
                return HttpNotFound();
            }
            return View(supplier);
        }

        
        //
        // POST: /Supplier/Edit/5

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Supplier supplier)
        {
            if (ModelState.IsValid)
            {
                db.Entry(supplier).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(supplier);
        }

        //
        // GET: /Supplier/Delete/5

        public ActionResult Delete(int id = 0)
        {
            Supplier supplier = db.Suppliers.Find(id);
            if (supplier == null)
            {
                return HttpNotFound();
            }
            return View(supplier);
        }

        //
        // POST: /Supplier/Delete/5

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Supplier supplier = db.Suppliers.Find(id);
            db.Suppliers.Remove(supplier);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

ClientSupplierMapper/Controllers/SupplierProductController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ClientSupplierMapper.Models;

namespace ClientSupplierMapper.Controllers
{
    public class SupplierProductController : Controller
    {
        private ClientSupplierMapperContextModel db = new ClientSupplierMapperContextModel();

        //
        // GET: /SupplierProduct/

        public ActionResult Index()
        {
            var suppliersproductmapper = db.SuppliersProductMapper.Include(s => s.Supplier).Include(s => s.Product);
            return View(suppliersproductmapper.ToList());
        }

        //
        // GET: /SupplierProduct/Details/5

        public ActionResult Details(int id = 0)
        {
            SupplierProductMapper supplierproductmapper = db.SuppliersProductMapper.Find(id);
            if (supplierproductmapper == null)
            {
                return HttpNotFound();
            }
            return View(supplierproductmapper);
        }

        //
        // GET: /SupplierProduct/Create

        public ActionResult Create()
        {
            ViewBag.ID_Supplier = new SelectList(db.Suppliers, "ID", "Name");
            ViewBag.ID_Product = new SelectList(db.Product, "ID", "Type");
            return View();
        }

        //
        // POST: /SupplierProduct/Create

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(SupplierProductMapper supplierproductmapper)
        {
            if (ModelState.IsValid)
            {
                db.SuppliersProductMapper.Add(supplierproductmapper);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.ID_Supplier = new SelectList(db.Suppliers, "ID", "Name", supplierproductmapper.ID_Supplier);
            ViewBag.ID_Product = new SelectList(db.Product, "ID", "Type", supplierproductmapper.ID_Product);
            return View(supplierproductmapper);
        }

        //
        // GET: /SupplierProduct/Edit/5

        public ActionResult Edit(int id = 0)
        {
            SupplierProductMapper supplierproductmapper = db.SuppliersProductMapper.Find(id);
            if (supplierproductmapper == null)
            {
                return HttpNotFound();
            }
            ViewBag.ID_Supplier = new SelectList(db.Suppliers, "ID", "Name", supplierproductmapper.ID_Supplier);
            ViewBag.ID_Product = new SelectList(db.Product, "ID", "Type", supplierproductmapper.ID_Product);
            return View(supplierproductmapper);
        }

        //
        // POST: /SupplierProduct/Edit/5

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(SupplierProductMapper supplierproductmapper)
        {
            if (ModelState.IsValid)
            {
                db.Entry(supplierproductmapper).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.ID_Supplier = new SelectList(db.Suppliers, "ID", "Name", supplierproductmapper.ID_Supplier);
            ViewBag.ID_Product = new SelectList(db.Product, "ID", "Type", supplierproductmapper.ID_Product);
            return View(supplierproductmapper);
        }

        //
        // GET: /SupplierProduct/Delete/5

        public ActionResult Delete(int id = 0)
        {
            SupplierProductMapper supplierproductmapper = db.SuppliersProductMapper.Find(id);
            if (supplierproductmapper == null)
            {
                return HttpNotFound();
            }
            return View(supplierproductmapper);
        }

        //
        // POST: /SupplierProduct/Delete/5

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            SupplierProductMapper supplierproductmapper = db.SuppliersProductMapper.Find(id);
            db.SuppliersProductMapper.Remove(supplierproductmapper);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

ClientSupplierMapper/Views/Supplier/AddInfo.cshtml
@model ClientSupplierMapper.Models.BigViewModel

@{
    ViewBag.Title = "Edit";
}

<h2>Add supplier product information</h2>

@using (Html.BeginForm()) {
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>Supplier</legend>

        @Html.HiddenFor(model => model.Suppliers.ID)

        <div class="editor-label">
            @Html.LabelFor(model => model.Suppliers.Name)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Product.Type)
            @Html.ValidationMessageFor(model => model.Product.Type)
        </div>

        <p>
            <input type="submit" value="Save" />
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("Back to List", "ViewSuppliers")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

ClientSupplierMapper/Views/Supplier/Create.cshtml
@model ClientSupplierMapper.Models.Supplier

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@using (Html.BeginForm()) {
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>Supplier</legend>

        <div class="editor-label">
            @Html.LabelFor(model => model.Name)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Name)
            @Html.ValidationMessageFor(model => model.Name)
        </div>

        <p>
            <input type="submit" value="Create" />
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

ClientSupplierMapper/Views/Supplier/Delete.cshtml
@model ClientSupplierMapper.Models.Supplier

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<fieldset>
    <legend>Supplier</legend>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Name)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Name)
    </div>
</fieldset>
@using (Html.BeginForm()) {
    @Html.AntiForgeryToken()
    <p>
        <input type="submit" value="Delete" /> |
        @Html.ActionLink("Back to List", "Index")
    </p>
}

ClientSupplierMapper/Views/Supplier/Details.cshtml
@model ClientSupplierMapper.Models.Supplier

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<fieldset>
    <legend>Supplier</legend>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Name)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Name)
    </div>
</fieldset>
<p>
    @Html.ActionLink("Edit", "Edit", new { id=Model.ID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

ClientSupplierMapper/Views/Supplier/Edit.cshtml
@model ClientSupplierMapper.Models.Supplier

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm()) {
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>Supplier</legend>

        @Html.HiddenFor(model => model.ID)

        <div class="editor-label">
            @Html.LabelFor(model => model.Name)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Name)
            @Html.ValidationMessageFor(model => model.Name)
        </div>

        <p>
            <input type="submit" value="Save" />
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

ClientSupplierMapper/Views/Supplier/Index.cshtml
@model IEnumerable<ClientSupplierMapper.Models.Supplier>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>

<p>
    @Html.ActionLink("View existing suppliers", "ViewSuppliers")
</p>
<table>
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Name)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.ID }) |
            @Html.ActionLink("Details", "Details", new { id=item.ID }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.ID })
        </td>
    </tr>
}

</table>

ClientSupplierMapper/Views/Supplier/ViewSuppliers.cshtml
@model IEnumerable<ClientSupplierMapper.Models.Supplier>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<table>
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Name)
        </td>
        <td>
            @Html.ActionLink("Add Info", "Create", "SupplierProduct" ,new { id=item.ID }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.ID })
        </td>
    </tr>
}

</table>